api_platform:
    title: Api Proyecto Llaves
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    # Mantener Swagger UI activo, desactivar ReDoc
    enable_swagger_ui: true
    enable_re_doc: false