gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000 # 30 d√≠as
    token_parameter_name: refresh_token
    user_identity_field: email
    return_expiration: false
    return_expiration_parameter_name: refresh_token_expiration
